# Generated by Django 5.0.2 on 2024-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='banner',
            field=models.CharField(default='مرحبا بكم', max_length=200),
        ),
    ]
