# Generated by Django 5.0.2 on 2024-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_indexpage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='slag',
            field=models.CharField(default='التعلم يبداء من مقال', max_length=200),
        ),
    ]
