# Generated by Django 5.0.2 on 2024-02-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_indexpage_supslag'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ما هو هدفنا ولماذا نطمح للوصول لكل العرب؟', max_length=200)),
                ('text1', models.CharField(default='لدينا هدف واحد وهو ان نثري المحتوى العربي بالمعلومات المفيدة وزيادة حجم المشاركة للمعلومات باللغة العربية', max_length=700)),
            ],
        ),
    ]
