# Generated by Django 5.0.2 on 2024-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0006_aboutpage_photo1_aboutpage_photo1alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='logo',
            field=models.ImageField(default='index_photos/LOGO.jpg', upload_to='index_photos/'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='logoalt',
            field=models.CharField(default='logo img', max_length=200),
        ),
    ]
