# Generated by Django 5.0.2 on 2024-02-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0007_indexpage_logo_indexpage_logoalt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='photo1',
            field=models.ImageField(default='about_photos/LOGO.jpg', upload_to='media/about_photos/'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='logo',
            field=models.ImageField(default='index_photos/LOGO.jpg', upload_to='media/index_photos/'),
        ),
    ]
